parknova:
  keycloak:
    base-url: ${KEYCLOAK_BASE_URL:https://keycloak-dev.eden-tech.io}
    realm: ${KEYCLOAK_REALM:parknova}
    client-id: ${KEYCLOAK_CLIENT_ID:parknova-api-gateway}
    client-secret: ${KEYCLOAK_CLIENT_SECRET:CHANGE_ME}
    jwt-decoder-enabled: true
  enforcer-keycloak:
    base-url: ${ENFORCER_KEYCLOAK_BASE_URL:${KEYCLOAK_BASE_URL:https://keycloak-dev.eden-tech.io}}
    realm: ${ENFORCER_KEYCLOAK_REALM:eden-crm-sec-users}

spring:
  cloud:
    gateway:
      mvc:
        routes:
          - id: parknova-offstreet-mobile
            uri: ${MOBILE_SERVICE_URI:http://localhost:8081}
            predicates:
              - Path=/client/**,/internal/**,/mobile/**,/enforcer/**
          - id: parknova-offstreet-service
            uri: ${OFFSTREET_SERVICE_URI:http://localhost:8090}
            predicates:
              - Path=/api/v1/**,/api/external/**,/customer/**

logging:
  level:
    com.parknova.parknovaapigateway: DEBUG
    org.springframework.security: DEBUG
